Update with FileBot Node 0.4.3 templates

diff --git a/node/opt/filebot-node/task b/node/opt/filebot-node/task
--- a/node/opt/filebot-node/task
+++ b/node/opt/filebot-node/task
@@ -1,6 +1,25 @@
-#!/bin/sh
+#!/bin/sh -u
 
-export DATA="$HOME/.filebot-node"
-export TASK="$1"
+export FILEBOT_NODE_DATA="$HOME/node"
+export FILEBOT_NODE_TASK="$1"
 
-filebot "@$DATA/task/$TASK.args" 2>&1 | tee -a "$DATA/log/$TASK.log"
+
+# import user environment
+if [ -f "$FILEBOT_NODE_DATA/environment.sh" ]; then
+	source "$FILEBOT_NODE_DATA/environment.sh"
+fi
+
+
+# execute filebot task and record output
+filebot "@$FILEBOT_NODE_DATA/task/$FILEBOT_NODE_TASK.args" 2>&1 | tee -a "$FILEBOT_NODE_DATA/log/$FILEBOT_NODE_TASK.log"
+
+
+# get filebot exit code (and not tee exit code)
+STATUS="${PIPESTATUS[0]}"
+
+# treat ExitCode.NOOP as ExitCode.SUCCESS
+if [ $STATUS -eq 100 ]; then
+	exit 0
+fi
+
+exit $STATUS
